apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: sre-configure-alertmanager-operator
  namespace: openshift-monitoring
spec:
  groups:
  - name: sre-configure-alertmanager-operator
    rules:
    - alert: ConfigureAlertmanagerOperatorMismatchDmsSRE
      annotations:
        message: "Mismatch between DMS secret and DMS AlertManager config"
        link_url: "https://access.redhat.com/articles/4165971"
      expr: dms_secret_exists + am_secret_contains_dms == 1
      for: 5m
      labels:
        severity: critical
    - alert: ConfigureAlertmanagerOperatorMismatchGaSRE
      annotations:
        message: "Mismatch between GA secret and GA AlertManager config"
        link_url: "https://access.redhat.com/articles/4165971"
      expr: ga_secret_exists + am_secret_contains_ga == 1
      for: 5m
      labels:
        severity: critical
    - alert: ConfigureAlertmanagerOperatorMismatchPdSRE
      annotations:
        message: "Mismatch between PD secret and PD AlertManager config"
        link_url: "https://access.redhat.com/articles/4165971"
      expr: pd_secret_exists + am_secret_contains_pd == 1
      for: 5m
      labels:
        severity: critical
    - alert: ConfigureAlertmanagerOperatorMissingAlermanagerConfigSRE
      annotations:
        message: "Alertmanager config secret does not exist"
        link_url: "https://access.redhat.com/articles/4165971"
      expr: am_secret_exists == 0
      for: 5m
      labels:
        severity: critical

