---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: configure-alertmanager-operator
  namespace: openshift-monitoring
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - "*"
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - "get"
  - "create"
- apiGroups:
  - apps
  resources:
  - deployments/finalizers
  resourceNames:
  - configure-alertmanager-operator
  verbs:
  - "update"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: configure-alertmanager-operator-view
rules:
- apiGroups:
  - config.openshift.io
  attributeRestrictions: null
  resources:
  - clusterversions
  verbs:
  - get
  - list
  - watch
- apiGroups:
    - config.openshift.io
  resources:
    - proxies
  verbs:
    - get
    - list
    - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: configure-alertmanager-operator-edit
rules:
- apiGroups:
  - ""
  attributeRestrictions: null
  resources:
  - secrets
  - configmaps
  verbs:
  - get
  - list
  - watch
  - patch
  - update
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - get
  - list
  - watch
